#ifndef WOLF_USER_SETTINGS_H
#define WOLF_USER_SETTINGS_H


#define XMALLOC_USER
#undef NO_PSK

#undef ALT_ECC_SIZE
//#define SMALL_SESSION_CACHE
#define USE_SLOW_SHA2
#define USE_SLOW_SHA
#define GCM_SMALL
#define NO_OLD_TLS
#define RSA_LOW_MEM
// #define CURVE25519_SMALL
#define WOLFSSL_SMALL_CERT_VERIFY
// #define WOLFSSL_SP_X86_64_ASM
// #define NO_OLD_POLY1305
#define NO_SESSION_CACHE
#define WOLFSSL_SP_MATH
#define WOLFSSL_SP_MATH_ALL
//#define WOLFSSL_SP_SMALL
//#define WOLFSSL_SP_NO_MALLOC
//#define WOLFSSL_SP_NO_DYN_STACK
// #undef WOLFSSL_SP_384
// #undef WOLFSSL_SP_521
// #undef WOLFSSL_SP_4096
// #define WOLFSSL_SP_NONBLOCK
#define WOLFSSL_HAVE_SP_RSA
#define WOLFSSL_HAVE_SP_ECC
#define WOLFSSL_HAVE_SP_DH
// #define WC_ECC_NONBLOCK
//#define FP_ECC
// #undef FAST_MATH
#define WC_ASN_NAME_MAX 128
#define WC_CTC_MAX_ALT_SIZE 128
#undef SESSION_CERTS
#undef HAVE_SESSION_TICKET
//#undef FP_ECC
#undef OPENSSL_EXTRA
#undef OPENSSL_ALL

#endif // WOLF_USER_SETTINGS_H
